### ISSUE TITLE
pinFromFS: More than one file and/or directory was provided for pinning

### ISSUE THREAD

**Issue by ilyaigpetrov** [PinataCloud/Pinata-SDK#11]
In the README it is said that `pinFromFS` works with directories but applying to `./dist` directory throws this error:
```js
[16:31:03] Error: More than one file and/or directory was provided for pinning.
    at /home/ilyaigpetrov/Projects/foobar-project/node_modules/@pinata/sdk/lib/pinata-sdk.js:22993:18
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

```js
const pin = () => {

  const pinataKey = process.env.PINATA_KEY;
  const pinataSecret = process.env.PINATA_SECRET;
  if (!pinataKey || !pinataSecret) {
    throw new Error('PINATA_KEY and PINATA_SECRET env variables are required!');
  }

  const pinata = pinataSDK(pinataKey, pinataSecret);

  const sourcePath = './dist';
  const options = {
    pinataMetadata: {
      name: `foobar`,
      keyvalues: {},
    },
  };
  return pinata.pinFromFS(sourcePath).then((result) => {

    console.log(result);
  });
};
```

**Comment by obo20** [comment]
@ilyaigpetrov thanks for the report. Could you try using an absolute path instead of the './dist' you're currently using? I'd like to see if that makes any difference for you

**Comment by ilyaigpetrov** [comment]
@obo20 full path works without issues.

**Comment by ilyaigpetrov** [comment]
`dist` also works, but `./dist` doesn't.

**Comment by obo20** [comment]
@ilyaigpetrov Apologies for the delay on getting back to you here. We've have a busy month at Pinata. Is there any chance you'd be able to upload a zip of your folder structure? I want to make absolutely sure that I'm testing in the same conditions that you are.

**Comment by obo20** [comment]
Hey all / @ilyaigpetrov I've fixed this issue and cut a new release for the sdk. Check out version 1.1.4 for this to be working correctly with `./` paths.

**Comment by jackjwilliams** [comment]
Sorry to rehash old issues but, I'm a little confused on the versioning scheme @obo20. 

I installed the latest release initially, which is 1.1.23 (release in June of 2021).

Back in Feb 2020 you released this 1.1.4 which fixed this issue (but in a newer version than is currently released?).

Ran into this issue but found I need to change to 1.1.4 maybe (which is a technically older version but higher number).

I just need to upload a folder, which version should I use? I get this same error on Windows 10 with 1.1.23.

**Comment by rusticphilosopher** [comment]
FYI, a related bug is still present in 1.1.23.  Running on windows 10, giving a path of "../mydir" results in a "invalid file path" error.  Passing the full path (example: "\Users\dir1\dir2\dir3\" works.

**Comment by ilyaigpetrov** [comment]
@rusticphilosopher 
1) `../mydir` (forward slash) fails.
2) `\Users\dir1\dir2\dir3` (backslash) works.

Guess: maybe you just need to use a backslash, not forward.

**Comment by shig2k1** [comment]
@rusticphilosopher Same for me. Which is super odd because a few hours ago it was working fine :-/

**Comment by jgrean81** [comment]
Agree, doesn't work as documentation suggests for this function. The entire documentation could use work to be blunt.
It reports "More than one file and/or directory was provided for pinning.". Yeah, no sh*t. The function is supposed to upload the contents of a dir. Wrapped, I assume though it still seems you need to actually specify that? When wrapped for such a function should be default. In any case, not sure because the function does nothing, beyond reporting there is more than 1 file. Yes, yes there is. And now what?

**Comment by JulienPlanchetCoineo** [comment]
> Agree, doesn't work as documentation suggests for this function. The entire documentation could use work to be blunt. It reports "More than one file and/or directory was provided for pinning.". Yeah, no sh*t. The function is supposed to upload the contents of a dir. Wrapped, I assume though it still seems you need to actually specify that? When wrapped for such a function should be default. In any case, not sure because the function does nothing, beyond reporting there is more than 1 file. Yes, yes there is. And now what?

Did you solve your issue ? 
I have the same result.

**Comment by witwit** [comment]
This is really a shame. Paying for premium account, hoping for the API to work. But it does not. You cannot pin directories. Please let us know how to handle it correctly (on different OS). Using an absolute path also put the absolute path into the URL. For example, if I pin: "C:\Users\user\myDir\dist" then the URL also includes the whole path "https://.../Qm.../Users/user/myDir/dist/"

That's bad.

**Comment by partyka1** [comment]
In my case this error was caused by having double slash in the path, ie `pinata.pinFromFS('/Users/partyka1/pinata//important/files')`, changing to `pinata.pinFromFS('/Users/partyka1/pinata/important/files')` helped. I'm using pinata js sdk on macos

**Comment by mihaidicianu** [comment]
I managed to find a **workaround** (although experiencing all the problems described here beforehand): the only way I could pin only a folder with multiple files in it is by providing a path that only contains the folder, i.e. `pinata.pinFromFS('./images')`, implicitly running the program from the same folder as the target one.

**Comment by SamM** [comment]
A possible work-around that solves the issue for me is to convert the relative path into an absolute path using node's path module:
`const sourcePath = require('path').resolve('./dist');`

**Comment by SamM** [comment]
Found a clue to why this might be happening in this answer to a question on stackoverflow (though it relates to uploading using python): https://stackoverflow.com/a/72077543/1309840 .
Apparently if the `name` specified in the pinataMetadata is the same as the name of the base folder in the path you are uploading it will not return the same `More than one file and/or directory was provided for pinning` error.
I have not tested this with the SDK yet, as I moved towards an axios approach to find a solution after having the same problem as talked about in this thread.

**Comment by SamM** [comment]
Seems to be an issue with the API endpoint as much as the SDK implementation

**Comment by damianlluch** [comment]
Hi, I'm having the same problem. Trying to upload more than one file from S3.


This is my code:


```
try {
      const form = new FormData();
      /** for (const item of items) {
        const file = getObjectStream(item.tokenURI, bucket, path); // return Readable objet
        form.append('file', file, {
          filename: item.tokenURI,
        });
      } **/

      const fileOne = getObjectStream(
        '_1_QDK5CsvMwd-9Q1rjFG.jpeg',
        bucket,
        path,
      );
      form.append('file', fileOne, {
        filename: '_1_QDK5CsvMwd-9Q1rjFG.jpeg',
      });
      const fileTwo = getObjectStream(
        '-OYIR4OQegkpxh4Xnoul8.jpeg',
        bucket,
        path,
      );

      form.append('file', fileTwo, {
        filename: '-OYIR4OQegkpxh4Xnoul8.jpeg',
      });

      console.log(`Uploading files to IPFS`);
      const pinataOptions: PinataOptions = {
        cidVersion: 1,
      };

      const config = {
        method: 'post',
        url: 'https://api.pinata.cloud/pinning/pinFileToIPFS',
        maxBodyLength: Infinity,
        headers: {
          pinata_api_key: 'XXXXXXXXXX',
          pinata_secret_api_key:
            'XXXXXXXXXXXX',
          ...form.getHeaders(),
        },
        data: form,
      };

      // @ts-ignore
      axios(config)
        .then(function (response) {
          console.log(JSON.stringify(response.data));
        })
        .catch(function (error) {
          console.log(error);
        });

      //console.log(`Piñata Response:`, JSON.stringify(result, null, 2));
      //return result.IpfsHash;
    } catch (e) {
      console.error(e);
    }
    ```


any suggestions?

**Comment by SamM** [comment]
You could try adding something like this, and change the someFolderNameGoesHere to whatever you want the directory to be called:
```
const pinataMetadata = {
  name: "someFolderNameGoesHere",
};
form.append('pinataMetadata', JSON.stringify(pinataMetadata));
```

**Comment by damianlluch** [comment]
> You could try adding something like this, and change the someFolderNameGoesHere to whatever you want the directory to be called:
> 
> ```
> const pinataMetadata = {
>   name: "someFolderNameGoesHere"
> };
> form.append('pinataMetadata', JSON.stringify(pinataMetadata));
> ```

Interesting approach, but I am not quite clear on what you are saying.
pinataMetadata as a key? why would I add that? you say to add that after adding the files?

**Comment by abrosua** [comment]
> Found a clue to why this might be happening in this answer to a question on stackoverflow (though it relates to uploading using python): https://stackoverflow.com/a/72077543/1309840 . Apparently if the `name` specified in the pinataMetadata is the same as the name of the base folder in the path you are uploading it will not return the same `More than one file and/or directory was provided for pinning` error. I have not tested this with the SDK yet, as I moved towards an axios approach to find a solution after having the same problem as talked about in this thread.

This answer solved it, but it's required to add the directory (defined in the metadata) to the URI (e.g., `gateway.pinata.cloud/ipfs/<CID>/<directory>/<filename>`). Is there a way to just use the `wrapWithDirectory=True` for pinning multiple files just like the standard IPFS API? So that the URI would be similar to this instead: `gateway.pinata.cloud/ipfs/<CID>/<filename>`
