### ISSUE TITLE
Property keyvalues cannot be assigned to PinataMetadata (ts2345)

### ISSUE THREAD

**Issue by kaoths** [PinataCloud/Pinata-SDK#68]
### Issue  

Property `keyvalues` cannot be assigned to `PinataMetadata`  

```typescript
export type PinataMetadata = Record<string, string | number | null>;
```
  
Incompatible with usage from document e.g. [here](https://github.com/PinataCloud/Pinata-SDK#hashmetadata)
<hr>  

### Example  

This following code
```typescript
const metadata = {
    name: "new custom name",
    keyvalues: {
      newKey: "newValue",
      existingKey: "newValue",
      existingKeyToRemove: null,
    },
  };
const response = await pinata.hashMetadata("yourHashHere", metadata);
console.log(response);
```
  
will produce following diagnostic error `ts2345`
```
Argument of type '{ name: string; keyvalues: { newKey: string; existingKey: string; existingKeyToRemove: null; }; }' is not assignable to parameter of type 'PinataMetadata'.
  Property 'keyvalues' is incompatible with index signature.
    Type '{ newKey: string; existingKey: string; existingKeyToRemove: null; }' is not assignable to type 'string | number | null'.
      Type '{ newKey: string; existingKey: string; existingKeyToRemove: null; }' is not assignable to type 'number'. ts(2345)
```
<hr>  

### Packages
`typescript` : `4.3.5`
`@pinata/sdk` : `1.1.23`
<hr>  

### Runtime
node: `14.17.3`
<hr>  

### System
macOS: Big Sur (v 11.4)
chip: Intel Core i5

**Comment by deepso7** [comment]
Any updates on this ?

**Comment by trivonhan** [comment]
@kaoths  Did you solve this? Can you give me a solution?

**Comment by kenshiru** [comment]
```
export type PinataPinOptions = {
    pinataMetadata?: Record<string, string | number | null> | undefined;
    pinataOptions?: PinataOptions | undefined;
};
```
Type for `keyvalues` type is not provided in typings here https://github.com/PinataCloud/Pinata-SDK/blob/master/types/index.d.ts#L225.

**Comment by rommel-pinata** [comment]
This issue was fixed in PR #130

**Comment by Tias84** [comment]
I'm having the same error using the function `pinata.PinJSONToIPFS`, it works but I still see the error. Here is a sample
```
const options = {
        pinataMetadata: {
            name: 'testName_04',
            keyvalues: {
                price: '5',
            }
        },
    }

const res = await pinata.pinJSONToIPFS(body, options)
```
